# Generated by Django 5.2.16 on 2026-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='behavioural_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
