# Generated by Django 5.2.16 on 2026-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_userpreference_behavioural_weights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='province',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
    ]
