# Generated by Django 5.2.16 on 2026-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_destination_image_url_province_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
