# Generated by Django 5.2.16 on 2026-07-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_itinerary_completed_itinerary_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(default='🚌', max_length=8)),
                ('base_fare_npr', models.PositiveIntegerField(default=0)),
                ('per_km_npr', models.FloatField(default=10.0)),
                ('speed_kmph', models.FloatField(default=40.0)),
                ('comfort', models.PositiveSmallIntegerField(default=3)),
                ('min_km', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['per_km_npr'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('price_npr', models.PositiveIntegerField(default=4000)),
                ('star_rating', models.FloatField(default=3.0)),
                ('lat', models.FloatField(default=28.0)),
                ('lng', models.FloatField(default=84.0)),
                ('image_url', models.URLField(blank=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.province')),
            ],
            options={
                'ordering': ['-star_rating', 'price_npr'],
            },
        ),
    ]
