"""Seed data: Nepal's 7 provinces and their famous spots with category-weight
feature vectors. Weights are in [0, 1] over CATEGORY_KEYS; only nonzero axes are
listed. Coordinates and costs are realistic but approximate.
"""

# order = official Province No. 1–7 (east → west), used by the home-map cycle.
PROVINCES = [
    {
        "name": "Koshi", "slug": "koshi", "order": 1,
        "center_lat": 27.30, "center_lng": 87.30,
        "spots": [
            {"name": "Everest Base Camp", "slug": "everest-base-camp",
             "lat": 27.98, "lng": 86.92, "cost_npr": 120000, "difficulty": 5,
             "best_season": "autumn",
             "w": {"trekking": 1.0, "adventure": 0.9, "hiking": 0.8, "popular": 0.9}},
            {"name": "Kanchenjunga Base Camp", "slug": "kanchenjunga-base-camp",
             "lat": 27.70, "lng": 88.15, "cost_npr": 110000, "difficulty": 5,
             "best_season": "autumn",
             "w": {"trekking": 1.0, "adventure": 0.9, "hiking": 0.7}},
            {"name": "Pathibhara Temple", "slug": "pathibhara-temple",
             "lat": 27.51, "lng": 87.78, "cost_npr": 8000, "difficulty": 3,
             "best_season": "all",
             "w": {"religious": 1.0, "hiking": 0.6, "popular": 0.7}},
            {"name": "Ilam Tea Gardens", "slug": "ilam-tea-gardens",
             "lat": 26.91, "lng": 87.93, "cost_npr": 12000, "difficulty": 2,
             "best_season": "spring",
             "w": {"hiking": 0.5, "popular": 0.6, "adventure": 0.2}},
        ],
    },
    {
        "name": "Madhesh", "slug": "madhesh", "order": 2,
        "center_lat": 26.80, "center_lng": 85.90,
        "spots": [
            {"name": "Janaki Temple", "slug": "janaki-temple",
             "lat": 26.73, "lng": 85.92, "cost_npr": 5000, "difficulty": 1,
             "best_season": "all",
             "w": {"religious": 1.0, "historic": 0.7, "popular": 0.8}},
            {"name": "Gadhimai Temple", "slug": "gadhimai-temple",
             "lat": 27.03, "lng": 85.00, "cost_npr": 4000, "difficulty": 1,
             "best_season": "all",
             "w": {"religious": 0.9, "historic": 0.4}},
            {"name": "Parsa National Park", "slug": "parsa-national-park",
             "lat": 27.28, "lng": 84.80, "cost_npr": 15000, "difficulty": 2,
             "best_season": "winter",
             "w": {"adventure": 0.6, "popular": 0.4, "hiking": 0.3}},
        ],
    },
    {
        "name": "Bagmati", "slug": "bagmati", "order": 3,
        "center_lat": 27.70, "center_lng": 85.40,
        "spots": [
            {"name": "Pashupatinath Temple", "slug": "pashupatinath-temple",
             "lat": 27.71, "lng": 85.35, "cost_npr": 6000, "difficulty": 1,
             "best_season": "all",
             "w": {"religious": 1.0, "historic": 0.7, "popular": 0.9}},
            {"name": "Boudhanath Stupa", "slug": "boudhanath-stupa",
             "lat": 27.72, "lng": 85.36, "cost_npr": 5000, "difficulty": 1,
             "best_season": "all",
             "w": {"religious": 0.9, "historic": 0.6, "popular": 0.9}},
            {"name": "Kathmandu Durbar Square", "slug": "kathmandu-durbar-square",
             "lat": 27.70, "lng": 85.30, "cost_npr": 5000, "difficulty": 1,
             "best_season": "all",
             "w": {"historic": 1.0, "religious": 0.6, "popular": 0.9}},
            {"name": "Chitwan National Park", "slug": "chitwan-national-park",
             "lat": 27.53, "lng": 84.45, "cost_npr": 22000, "difficulty": 2,
             "best_season": "winter",
             "w": {"adventure": 0.9, "popular": 0.9, "hiking": 0.4}},
            {"name": "Nagarkot", "slug": "nagarkot",
             "lat": 27.72, "lng": 85.52, "cost_npr": 9000, "difficulty": 2,
             "best_season": "autumn",
             "w": {"hiking": 0.7, "adventure": 0.4, "popular": 0.7}},
        ],
    },
    {
        "name": "Gandaki", "slug": "gandaki", "order": 4,
        "center_lat": 28.40, "center_lng": 84.00,
        "spots": [
            {"name": "Phewa Lake, Pokhara", "slug": "phewa-lake-pokhara",
             "lat": 28.21, "lng": 83.96, "cost_npr": 8000, "difficulty": 1,
             "best_season": "all",
             "w": {"popular": 1.0, "adventure": 0.6}},
            {"name": "Annapurna Base Camp", "slug": "annapurna-base-camp",
             "lat": 28.53, "lng": 83.88, "cost_npr": 90000, "difficulty": 5,
             "best_season": "autumn",
             "w": {"trekking": 1.0, "adventure": 0.9, "hiking": 0.8, "popular": 0.8}},
            {"name": "Muktinath Temple", "slug": "muktinath-temple",
             "lat": 28.82, "lng": 83.87, "cost_npr": 35000, "difficulty": 3,
             "best_season": "autumn",
             "w": {"religious": 1.0, "trekking": 0.6, "hiking": 0.5, "popular": 0.7}},
            {"name": "Poon Hill, Ghorepani", "slug": "poon-hill-ghorepani",
             "lat": 28.40, "lng": 83.69, "cost_npr": 45000, "difficulty": 4,
             "best_season": "spring",
             "w": {"trekking": 0.9, "hiking": 0.9, "popular": 0.8}},
            {"name": "Sarangkot", "slug": "sarangkot",
             "lat": 28.24, "lng": 83.95, "cost_npr": 10000, "difficulty": 2,
             "best_season": "autumn",
             "w": {"adventure": 0.7, "hiking": 0.6, "popular": 0.8}},
        ],
    },
    {
        "name": "Lumbini", "slug": "lumbini", "order": 5,
        "center_lat": 27.60, "center_lng": 82.80,
        "spots": [
            {"name": "Lumbini, Birthplace of Buddha", "slug": "lumbini-buddha",
             "lat": 27.47, "lng": 83.28, "cost_npr": 9000, "difficulty": 1,
             "best_season": "all",
             "w": {"religious": 1.0, "historic": 0.9, "popular": 0.9}},
            {"name": "Tansen, Palpa", "slug": "tansen-palpa",
             "lat": 27.87, "lng": 83.55, "cost_npr": 11000, "difficulty": 2,
             "best_season": "autumn",
             "w": {"historic": 0.7, "hiking": 0.4, "popular": 0.5}},
            {"name": "Bardia National Park", "slug": "bardia-national-park",
             "lat": 28.38, "lng": 81.50, "cost_npr": 25000, "difficulty": 2,
             "best_season": "winter",
             "w": {"adventure": 0.9, "popular": 0.6, "hiking": 0.3}},
            {"name": "Swargadwari", "slug": "swargadwari",
             "lat": 28.01, "lng": 82.61, "cost_npr": 9000, "difficulty": 3,
             "best_season": "all",
             "w": {"religious": 0.8, "hiking": 0.5}},
        ],
    },
    {
        "name": "Karnali", "slug": "karnali", "order": 6,
        "center_lat": 29.30, "center_lng": 82.20,
        "spots": [
            {"name": "Rara Lake", "slug": "rara-lake",
             "lat": 29.52, "lng": 82.08, "cost_npr": 55000, "difficulty": 4,
             "best_season": "autumn",
             "w": {"popular": 0.9, "hiking": 0.7, "trekking": 0.7, "adventure": 0.6}},
            {"name": "Shey Phoksundo Lake", "slug": "shey-phoksundo-lake",
             "lat": 29.19, "lng": 82.94, "cost_npr": 80000, "difficulty": 5,
             "best_season": "autumn",
             "w": {"trekking": 0.9, "adventure": 0.8, "hiking": 0.8, "popular": 0.7}},
            {"name": "Jumla", "slug": "jumla",
             "lat": 29.28, "lng": 82.18, "cost_npr": 30000, "difficulty": 3,
             "best_season": "summer",
             "w": {"historic": 0.4, "hiking": 0.5, "adventure": 0.3}},
        ],
    },
    {
        "name": "Sudurpashchim", "slug": "sudurpashchim", "order": 7,
        "center_lat": 29.30, "center_lng": 80.90,
        "spots": [
            {"name": "Khaptad National Park", "slug": "khaptad-national-park",
             "lat": 29.38, "lng": 81.13, "cost_npr": 40000, "difficulty": 3,
             "best_season": "summer",
             "w": {"hiking": 0.8, "adventure": 0.6, "religious": 0.5, "popular": 0.5}},
            {"name": "Badimalika Temple", "slug": "badimalika-temple",
             "lat": 29.60, "lng": 81.50, "cost_npr": 45000, "difficulty": 4,
             "best_season": "summer",
             "w": {"religious": 1.0, "trekking": 0.6, "hiking": 0.7}},
            {"name": "Api Himal Base Camp", "slug": "api-himal-base-camp",
             "lat": 30.00, "lng": 80.92, "cost_npr": 85000, "difficulty": 5,
             "best_season": "autumn",
             "w": {"trekking": 1.0, "adventure": 0.9, "hiking": 0.8}},
            {"name": "Ghodaghodi Lake", "slug": "ghodaghodi-lake",
             "lat": 28.69, "lng": 80.94, "cost_npr": 7000, "difficulty": 1,
             "best_season": "winter",
             "w": {"popular": 0.4, "adventure": 0.3}},
        ],
    },
]
